/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_timmyovo_winglobalhotkey_WinGlobalHotkeyAPI */

#ifndef _Included_com_github_timmyovo_winglobalhotkey_WinGlobalHotkeyAPI
#define _Included_com_github_timmyovo_winglobalhotkey_WinGlobalHotkeyAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_timmyovo_winglobalhotkey_WinGlobalHotkeyAPI
 * Method:    registerHotkey
 * Signature: (ILjava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_com_github_timmyovo_winglobalhotkey_WinGlobalHotkeyAPI_registerHotkey
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
